### ISSUE TITLE
Having trouble with crash analysis

### ISSUE THREAD

**Issue by caiello3** [cyrusbuilt/SAMCrashMonitor#1] opened 2020-01-29 08:02 UTC
I'm trying to follow the crash analysis instructions from the original repo (https://github.com/cyrusbuilt/ArduinoCrashMonitor#crash-analysis) but it is not working. I run the command and get the following error: "Access is denied."

Additionally I do not see any crash report details dumped to the serial monitor after the board restarts.

It's possible I'm not doing something correct and just need more guidance.

![image](https://user-images.githubusercontent.com/16707260/73338024-a3688700-4243-11ea-8f7d-09af0293645b.png)

**Comment by cyrusbuilt** [comment] 2020-01-29 12:01
avr-objdump was meant to be used with AVR binaries so it won't work with SAM binaries.  It looks like the tool you want is called 'arm-none-eabi-objdump'.  I think the basic usage is 'arm-none-eabi-objdump -t path_to_ELF'.  I don't think that tool is located in the same path though. Maybe ..\hardware\tools\sam\bin?  I'm not familiar with the paths on Windows since all my dev environments are on macOS and Linux.  That being said, this library won't dump any meaningful crash data other than the reset flag and description.  I does not capture any special boot flags or crash registers.

The original ArduinoCrashMonitor library installs an ISR under the hood that captures some state data from certain registers provided by the Arduino core for AVR and writes a 'crash report' of sorts to the EEPROM.  ESP version doesn't do this at all because the Arduino core for ESP does this automatically on every boot. The crash monitor on ESP simply reads boot flags the framework already provides and dumps them plus any available description.  MOST of what all 3 of these libraries does is implement the Watchdog functionality and provide a means of detecting a hang during execution and automatically reboot the MCU if that happens.

I have not yet figured out how to implement something similar on the SAM D21/D51.  Although this here looks promising: [https://microchipdeveloper.com/32arm:samd21-nvic-configuration](https://microchipdeveloper.com/32arm:samd21-nvic-configuration).  I may be able to provide more than just the reset reason flags.  Let me look into this a little further.  It may just be a matter of installing an ISR for the TC3 interrupt and capturing the values in the OVF/ERR registers.  Configuration is very similar to the WDT interrupt.

**Comment by cyrusbuilt** [comment] 2020-01-29 12:03
Does the watchdog functionality at least work on the SAM D21?  Meaning, does it reset on hang and then dump the reset code upon reboot?

**Comment by cyrusbuilt** [comment] 2020-01-29 14:06
Turns out, the Microchip SAM D21 SDK that the Arduino framework wraps under the hood has a weakly defined HardFault_Handler routine which I can override (just like WDT_Handler does) to capture stack frames when a hard fault occurs and then record the register values as a crash report in EEPROM which we can then read on boot, just like in the original ArduinoCrashMonitor library. Unlike the AVR though, SAM uses separate interrupts for all kinds of things. I'll have to sort of merge handling of both the watchdog interrupt and fault interrupts into a single function, then generate a single crash report and record it. I should also be able to provide a means of setting a user-defined crash handler that ultimately gets called once all the internal processing is finished. This would allow you to decide what to do when a crash occurs (reboot, halt, etc) or simply do a soft-reboot if no handler is defined. The PC (program counter) register will contain the address of the instruction that was executing when a hard fault occurs. Having this address will tell you where the failure is happening which you can then look up against the disassembly to find out where the issue is.  I'll have to re-write this API a bit to make all this work.  Bear with me while I figure all this out.

**Comment by caiello3** [comment] 2020-01-29 15:42
sounds good. let me know anything I can do to help test along the way. the offer for me to ship you a board still stands, just in case that would help as you work through this stuff rather than relying on me at these early stages (but I'm still happy to help any way I can). I do have access to a mac as well if that makes it easier for you to direct me how exactly to test this going forward. thanks for your work on this!

**Comment by cyrusbuilt** [comment] 2020-01-30 23:59
I just realized something.... The SAM D21 doesn't have an EEPROM.  So there is no where to store the crash reports.  I basically have 2 options:

Add a bunch of EEPROM emulation code to treat the onboard flash as EEPROM (similar to this library: [https://github.com/cmaglie/FlashStorage/blob/master/src/FlashAsEEPROM.h](https://github.com/cmaglie/FlashStorage/blob/master/src/FlashAsEEPROM.h))

- or -

Dump the crash reports to serial *prior* to resetting the MCU.  Generally speaking though, you don't typically want to attempt to write to the serial port in an ISR, especially if there is something wrong with the serial port that caused the crash in the first place or if some other global state problem prevents it.

I'm honestly not sure which approach I want to take.

**Comment by cyrusbuilt** [comment] 2020-01-31 11:40
Ok just merged my latest changes. Pull down the latest version of master and test it out per the example code. Watchdog functionality should still behave the same, but now it also installs a hard fault handler which will then dump a crash report containing the values of all the relevant registers to Serial. The main one you will be interested in is ":pc=0x[some value]" which is the address of the instruction that was executing when the hard fault occurred. According to the documentation though, this address is only worth something if it is what they call a "precise" fault. An *imprecise* fault is much trickier to figure out apparently.

My guess is, after initializing the library, you could intentionally cause a divide-by-zero fault by doing something like this:

int thisShouldCrash = 5 / 0;

Which *should* cause a crash to dump out to the serial port right before it resets the MCU.

**Comment by caiello3** [comment] 2020-02-04 05:46
ok I was finally able to get time to do some testing and it appears to be successfully resetting once the sketch crashes, but I'm not seeing anything get dumped out to the serial port before it resets. Not sure where to go from here. There could still be some error on my part. Below is the code as I was testing it. I thought I should be able to comment out both of the tests in the setup but when I did that the it appeared to just reset in a loop (the strings that should be printed to the serial monitor in the loop never printed).

Not sure where to go from here? I could set up a webex meeting that we can screen share so you can see what I am testing. Just a thought.

Here is the code I was testing:
`
#include <Arduino.h>
#include "SAMCrashMonitor.h"

void setup() {
  Serial.begin(9600);
  Serial.println();
  SAMCrashMonitor::begin();
  SAMCrashMonitor::dump();
  Serial.println();

  Serial.println(F("Enabling watchdog."));
  int timeout = SAMCrashMonitor::enableWatchdog(4000);
  Serial.print(F("Watchdog enabled for "));
  Serial.print(timeout);
  Serial.println(" ms.");

// I thought I'd be able to comment out the tests starting here, but then it appeared that the loop never ran
  Serial.println();
  Serial.println(F("First test: Looping once per second for 5 seconds while feeding watchdog..."));
  for (int i = 1; i <= 5; i++) {
    Serial.print(F("Loop #"));
    Serial.println(i);
    delay(1000);
    SAMCrashMonitor::iAmAlive();
  }
  /*
     Serial.println();
     Serial.println(F("Disabling watchdog..."));
     Serial.println();
     SAMCrashMonitor::disableWatchdog();

     Serial.println(F("Second test: Exceed timeout and reset."));
     timeout = SAMCrashMonitor::enableWatchdog(4000);
     Serial.print(F("Watchdog will reset controller in "));
     Serial.print(timeout);
     Serial.println(" ms!");
     delay(timeout + 1000);
  */
  // We shouldn't get this far since the watchdog should reset the MCU.
}

void loop() {
  SAMCrashMonitor::iAmAlive();
  Serial.println("hello");

  //int thisShouldCrash = 5 / 0;
  Serial.println("The end is here. Goodbye cruel world.");
  delay(2000);
  while (true) {  //this is where it should crash
    ;;
  }
}
`

**Comment by cyrusbuilt** [comment] 2020-02-04 18:01
When it resets due to the Watchdog timing out (not due to a Hard Fault), then it should dump the reset reason on during setup() upon reset.  This, of course, means it is crucial to call Serial.begin(whatever_baud_rate), prior to calling SAMCrashMonitor::dump().  I see that you are doing that, so are you not seeing the reset cause being printed when dump() is called?

**Comment by caiello3** [comment] 2020-02-04 22:35
I believe that is correct (I'm not seeing the reset cause being printed). But I'm not sure how to be certain that SAMCrashMonitor::dump() is being called. I assume that it gets called after the watchdog timeout (currently set to 4000ms) happens.

Also, I'm not sure how to get it running without the test code that is in the setup in the example, if you see my comment on line 17.

**Comment by cyrusbuilt** [comment] 2020-02-05 14:20
You are calling dump() in setup(), based on the code you've provided. That's troubling though. You should at least be seeing at least *some* output like this:

=========================================
Reset reason:
=========================================

Even if it doesn't give the actual reason, because that output is generated using plain old Serial.print() and Serial.println() calls.

**Comment by cyrusbuilt** [comment] 2020-02-05 14:23
Crap. Wait a minute.  That's my fault.  Apparently on the SAM D21, you are supposed to use SerialUSB instead of Serial when you want to output to the serial interface that connects to your computer.  I didn't notice that in the Arduino Framework documentation for the M0.  I'll fix it and merge in the changes.

**Comment by cyrusbuilt** [comment] 2020-02-05 14:42
Ok. I've merged the latest changes into master. Try out the example sketch and let me know if that works.

**Comment by caiello3** [comment] 2020-02-06 07:27
definitely making progress. I am now seeing the Reset reason, but I'm not sure it's working quite right yet. As you can see from the timestamp shown in the serial monitor, it is reporting a reset reason, but that is happening at the very beginning. Based on my code, it should be crashing 6 second after the start of the loop(). So I expected the Reset reason to appear in the serial monitor 2 seconds after the last line shown in the serial monitor, when it actually crashes. So I'm not sure what the Reset reason shown at the beginning is even related to.

The watchdog timeout appears to be working, as it seems to be resetting approximately 8 seconds after the board is restarted. But the thing that is not as I expected, is that once it resets, there is nothing new printing to the serial monitor. It just continues to show the first run's data in a static manner. Also, it never seems to actually make it through another loop. This is based on the sounds coming through my computer when it detects the board connecting and disconnection (admittedly not the best test). But after it ostensibly resets nothing else seems to happen.

![image](https://user-images.githubusercontent.com/16707260/73914099-83117b80-4886-11ea-9a73-8e28d5661a29.png)

**Comment by cyrusbuilt** [comment] 2020-02-06 14:27
It reports the reason at the beginning intentionally.  This is because the reset flag gets set in the MCU just prior to reboot. So we read that flag when the system boots back up and you set it as the first block of output when the MCU starts up because dump() is being called right after SerialUSB initialization in setup().  The timeout you set is for 8 seconds. So it would be 8 seconds after the last line printed is when the timeout threshold would be hit.  You have a delay occurring for 2 seconds before the while loop, so about 6 seconds of looping would cause it.  Unless I'm missing a piece of information it looks like it is working correctly. Let it run for a couple of loops and let me see the output. The output from one loop isn't enough to tell me what is happening.  Another thing I should look into is on some boards, delay() internally feeds the Watchdog so that it doesn't trip due to *intentional* delays (such as on the ESPs).  I'm not 100% certain this isn't happening on the SAM D21, but everything I've read so far looks like it isn't (meaning a delay() call longer than your timeout should cause a reset).

**Comment by caiello3** [comment] 2020-02-06 15:40
ok that makes sense and I agree that it seems to be working. I'm not sure how to change my code to allow it to run through the loop several times before crashing- any suggestions?

**Comment by cyrusbuilt** [comment] 2020-02-06 17:08
Oh does it clear the console every time it resets?  If so, then I'm not sure. If not, then just let it reboot and it should start outputting on each loop.  AVR and ESP-based MCUs attached to PlatformIO's serial monitor don't clear on reset.  I haven't used the Arduino IDE for quite some time but I don't think it cleared with those either.  I don't have any real experience with their behavior with a SAM D21 though.  Maybe there is a setting in the Arduino IDE?

**Comment by caiello3** [comment] 2020-02-07 22:45
yeah that's the problem I'm having. every time it reboots it clears the
serial monitor and for some reason after the reboot it does not start
outputting to the serial monitor again. oddly enough it does start
outputting to the serial monitor if I do a hard reset with the button. I
know you are using a mac, I also have a mac (just not my primary device).
Do you have any recommendations for a different IDE I could try on either
mac or windows that may not clear the serial monitor? I'll do some research
and testing too, but will be happy to try any [free] recommendations you
may have,

**Comment by cyrusbuilt** [comment] 2020-02-08 17:34
My personal preference is [PlatformIO](https://platformio.org/).  I've used pretty much every Arduino development platform there is and that one is by far my favorite.  It is basically a set of extensions for Visual Studio Code. Which means it is cross-platform.  It also support a massive variety of boards, frameworks, and platforms.  All the Arduino variants, Microchip, PIC, RaspberryPI, etc.  It also has command line tools, IntelliSense, library management, project structure init, and so-on.  It of course also has a Serial monitor.  I couldn't tell you if it will work better than the Arduino IDE's Serial monitor, but pretty every else about it is better, so its worth a shot.  Also, it's free and open source.

**Comment by caiello3** [comment] 2020-02-19 06:50
I was finally able to find a way to show multiple loops in the serial monitor (using an app called [CoolTerm](https://freeware.the-meiers.org/?utm_source=platformio&utm_medium=docs)).

Here is the output from several successive loops:


=========================================

Reset reason: 16, External reset requested
=========================================

Enabling watchdog.
Watchdog enabled for 8000 ms.
hello
The end is here. Goodbye cruel world.
did I make it this far?

=========================================

Reset reason: 32, Reset requested by Watchdog
=========================================

Enabling watchdog.
Watchdog enabled for 8000 ms.
hello
The end is here. Goodbye cruel world.
did I make it this far?

=========================================

Reset reason: 32, Reset requested by Watchdog
=========================================

Enabling watchdog.
Watchdog enabled for 8000 ms.
hello
The end is here. Goodbye cruel world.
did I make it this far?

=========================================

Reset reason: 32, Reset requested by Watchdog
=========================================

Enabling watchdog.
Watchdog enabled for 8000 ms.
hello
The end is here. Goodbye cruel world.
did I make it this far?

=========================================

Reset reason: 32, Reset requested by Watchdog
=========================================

Enabling watchdog.
Watchdog enabled for 8000 ms.
hello
The end is here. Goodbye cruel world.
did I make it this far?

=========================================

Reset reason: 32, Reset requested by Watchdog
=========================================

Enabling watchdog.
Watchdog enabled for 8000 ms.
hello
The end is here. Goodbye cruel world.
did I make it this far?

=========================================

Reset reason: 32, Reset requested by Watchdog
=========================================

Enabling watchdog.
Watchdog enabled for 8000 ms.
hello
The end is here. Goodbye cruel world.
did I make it this far?

**Comment by cyrusbuilt** [comment] 2020-02-19 15:15
It looks like it is resetting like it is supposed to.  I'm just super confused as to how it is printing that last line since it comes after an infinite loop.

**Comment by caiello3** [comment] 2020-02-24 06:49
yes best I can tell it is working correctly, although I don't understand that last line either.

**Closed as completed** 2020-02-27 13:28 UTC
Labels: bug
